<?php
/**
 * OSINT Universal Intelligence Console — Unified Execution & Premium Blueprint
 * File: report.php
 * Style Profile: Premium Whitebridge Corporate Dossier Blueprint + Background Worker Trigger
 */
require_once 'config.php';

if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// 1. INBOUND WORKSPACE STATE VALIDATION
$vid = isset($_REQUEST['id']) ? trim($_REQUEST['id']) : ''; 
if (empty($vid)) {
    die("<pre>[SYSTEM SHUTDOWN] Critical Exception: Missing parameter ?id= target workspace token.</pre>");
}

// 2. FETCH CORE DATA LAYERS FROM BASELINE SCHEMAS (VIEW MATRIX)
$stmt = $pdo->prepare("SELECT `name`, `input_email`, `avatar`, `social_urls` FROM `view` WHERE `vid` = ? LIMIT 1");
$stmt->execute([$vid]);
$target = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$target) {
    die("<pre>[SYSTEM SHUTDOWN] Data Integrity Failure: View vector coordinates missing for VID: " . htmlspecialchars($vid) . "</pre>");
}

$reportStmt = $pdo->prepare("SELECT * FROM `reports` WHERE `vid` = ? LIMIT 1");
$reportStmt->execute([$vid]);
$report = $reportStmt->fetch(PDO::FETCH_ASSOC);

if (!$report) {
    $insert = $pdo->prepare("INSERT INTO `reports` (`vid`, `uid`, `status`, `created_at`) VALUES (?, ?, 'pending', NOW())");
    $insert->execute([$vid, isset($_SESSION['user_id']) ? (int)$_SESSION['user_id'] : null]);
    
    $reportStmt->execute([$vid]);
    $report = $reportStmt->fetch(PDO::FETCH_ASSOC);
}

$status = $report['status'] ?? 'pending';

// =========================================================================
// ASYNCHRONOUS ORCHESTRATION GATE: TRIGGER BRAIN WORKER IF PENDING
// =========================================================================
if ($status === 'pending' || isset($_GET['force_rebuild'])) {
    $pdo->prepare("UPDATE `reports` SET `status` = 'processing', `updated_at` = NOW() WHERE `vid` = ?")->execute([$vid]);
    
    if (function_exists('shell_exec')) {
        $cmd = "php " . __DIR__ . "/process.php id=" . escapeshellarg($vid) . " > /dev/null 2>&1 &";
        shell_exec($cmd);
    } else {
        if (file_exists('process.php')) {
            $argv = [ 'process.php', 'id=' . $vid ];
            include 'process.php';
        }
    }
    $status = 'processing';
}

// =========================================================================
// DYNAMIC ACCRUED VALIDITY TIME HORIZON MATRIX COMPUTATION
// =========================================================================
$daysRemaining = 30; 
if (!empty($report['created_at'])) {
    $creationTimestamp = strtotime($report['created_at']);
    $currentTimestamp  = time();
    $elapsedSeconds    = $currentTimestamp - $creationTimestamp;
    $elapsedDays       = floor($elapsedSeconds / (60 * 60 * 24));
    $daysRemaining     = 30 - $elapsedDays;
    if ($daysRemaining < 0) { $daysRemaining = 0; }
}

function escapeHtml($str) {
    return htmlspecialchars($str ?? '', ENT_QUOTES, 'UTF-8');
}

// Pull data strictly and solely out of the social_urls tracking sequence maps
$socialLinks = [];
if (!empty($target['social_urls'])) {
    foreach (explode(',', $target['social_urls']) as $part) {
        $trimmed = trim($part);
        if (!empty($trimmed) && !in_array($trimmed, $socialLinks)) { 
            $socialLinks[] = $trimmed; 
        }
    }
}

function getSocialIconClass($url) {
    $lower = strtolower($url);
    if (strpos($lower, 'facebook.com') !== false || strpos($lower, 'fb.com') !== false) return 'fa-brands fa-facebook text-blue-600 text-lg';
    if (strpos($lower, 'instagram.com') !== false) return 'fa-brands fa-instagram text-pink-600 text-lg';
    if (strpos($lower, 'linkedin.com') !== false) return 'fa-brands fa-linkedin text-blue-700 text-lg';
    if (strpos($lower, 'twitter.com') !== false || strpos($lower, 'x.com') !== false) return 'fa-brands fa-x-twitter text-slate-900 text-lg';
    if (strpos($lower, 'tiktok.com') !== false) return 'fa-brands fa-tiktok text-slate-950 text-lg';
    return 'fa-solid fa-link text-slate-400 text-lg';
}

// =========================================================================
// DYNAMIC META DATA PREPARATION ENGINE
// =========================================================================
$dynamicTargetName = !empty($target['name']) ? escapeHtml($target['name']) : 'Identity Target';
$pageTitle = $dynamicTargetName . " - Intelligence Report - Identity Search AI";
$metaDescription = "Access the comprehensive open-source intelligence dossier and digital footprint analysis report compiled for " . $dynamicTargetName . ". This report was generated by idtrace.ai";

// Fallback configuration parameters if the profile does not possess an active avatar path string
$resolvedMetaImageUrl = 'https://cdn-icons-png.flaticon.com/512/149/149071.png';
if (!empty($target['avatar'])) {
    $resolvedMetaImageUrl = rtrim(BASE_URL, '/') . '/' . ltrim($target['avatar'], '/');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <title><?= $pageTitle ?></title>
    
    <!-- DYNAMIC SEO META ARCHITECTURE SEED MODULE -->
    <meta name="description" content="<?= $metaDescription ?>">
    
    <!-- OPEN GRAPH ENGINE ROUTING SCHEMAS -->
    <meta property="og:title" content="<?= $pageTitle ?>">
    <meta property="og:description" content="<?= $metaDescription ?>">
    <meta property="og:image" content="<?= $resolvedMetaImageUrl ?>">
    <meta property="og:type" content="profile">
    
    <!-- TWITTER Dossier Card Struct Layout Matrix -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="<?= $pageTitle ?>">
    <meta name="twitter:description" content="<?= $metaDescription ?>">
    <meta name="twitter:image" content="<?= $resolvedMetaImageUrl ?>">

    <?php include 'head.php'; ?>
    <style>
        body { background-color: #ffffff !important; color: #1e293b !important; }
        .pulse-glow { animation: pulseGlow 2.5s infinite; }
        @keyframes pulseGlow { 0%, 100% { opacity: 1; } 50% { opacity: .5; } }
        
        @media print {
            nav, footer, .print-hidden-node, button, .validity-bar-node { display: none !important; }
            body { background: #ffffff !important; padding: 0 !important; font-size: 12px; }
            main { max-width: 100% !important; width: 100% !important; padding: 0 !important; margin: 0 !important; space-y: 1rem !important; }
            .top-profile-card { break-inside: avoid-page !important; page-break-inside: avoid !important; margin-bottom: 1rem !important; }
        }
    </style>
</head>
<body class="min-h-screen flex flex-col justify-between selection:bg-slate-900 selection:text-white">

    <?php include 'navbar.php'; ?>
    
    <main class="max-w-3xl w-full mx-auto px-6 pt-10 pb-20 flex-grow space-y-6">

        <!-- =========================================================================
             TOP SECTION: TARGET PROFILE CARD
             ========================================================================= -->
        <div class="top-profile-card bg-slate-50 border border-slate-100 rounded-2xl p-6 sm:p-8 flex flex-col sm:flex-row items-center gap-6 text-center sm:text-left shadow-sm">
            <?php if (!empty($target['avatar'])): 
                $resolvedAvatarUrl = rtrim(BASE_URL, '/') . '/' . ltrim($target['avatar'], '/');
            ?>
                <div class="w-20 h-20 rounded-2xl overflow-hidden border border-slate-200 shrink-0 shadow-2sm">
                    <img src="proxy.php?url=<?= urlencode(base64_encode($resolvedAvatarUrl)) ?>" class="w-full h-full object-cover" onerror="this.src='https://cdn-icons-png.flaticon.com/512/149/149071.png';">
                </div>
            <?php endif; ?>
            
            <div class="space-y-2 flex-grow min-w-0 w-full">
                <div class="space-y-0.5">
                    <h1 class="text-2xl font-bold tracking-tight text-slate-900 truncate"><?= $dynamicTargetName ?></h1>
                    <?php if (!empty($target['input_email'])): ?>
                        <p class="text-xs text-slate-500 font-medium truncate"><i class="fa-solid fa-envelope mr-1.5 text-slate-400"></i><?= escapeHtml($target['input_email']) ?></p>
                    <?php endif; ?>
                </div>

                <?php if (!empty($socialLinks)): ?>
                    <div class="flex flex-wrap items-center justify-center sm:justify-start gap-2.5 pt-0.5">
                        <?php foreach ($socialLinks as $link): ?>
                            <a href="<?= escapeHtml($link) ?>" target="_blank" class="w-8 h-8 rounded-lg bg-white border border-slate-200 shadow-3sm hover:border-slate-300 flex items-center justify-center transition" title="<?= escapeHtml($link) ?>">
                                <i class="<?= getSocialIconClass($link) ?>"></i>
                            </a>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
        </div>

        <!-- =========================================================================
             ACTION INTERACTION BAR: SAVE AND SHARE ENGINES
             ========================================================================= -->
        <?php if ($status === 'completed'): ?>
            <div class="validity-bar-node flex items-center justify-between border border-slate-100 rounded-xl p-6 bg-slate-50 shadow-sm print:hidden gap-4 flex-wrap sm:flex-nowrap">
                <div class="text-left space-y-0.5">
                    <span class="text-slate-500 font-medium text-xs block">Your report will expire in</span>
                    <span class="text-blue-600 font-bold text-xs flex items-center gap-1">
                        <i class="fa-regular fa-clock text-[11px]"></i> <?= (int)$daysRemaining ?> <?= ($daysRemaining === 1) ? 'day' : 'days' ?>
                    </span>
                </div>
                <div class="flex items-center gap-2 w-full sm:w-auto justify-end">
                    <button onclick="if(navigator.share){ navigator.share({title: document.title, url: window.location.href}); } else { navigator.clipboard.writeText(window.location.href); alert('Link copied to clipboard!'); }" class="bg-slate-900 hover:bg-black text-white font-semibold text-xs px-4 py-2.5 rounded-lg transition flex items-center gap-1.5 cursor-pointer shadow-sm active:scale-[0.98]">
                        <i class="fa-regular fa-share-from-square"></i> Share
                    </button>
                    <button onclick="window.print();" class="bg-blue-500 hover:bg-blue-600 text-white font-semibold text-xs px-4 py-2.5 rounded-lg transition flex items-center gap-1.5 cursor-pointer shadow-sm active:scale-[0.98]">
                        <i class="fa-regular fa-file-pdf"></i> Save
                    </button>
                </div>
            </div>
        <?php endif; ?>

        <!-- Spacer Divider to preserve design layout consistency -->
        <div class="pt-2 print:hidden"></div>

        <!-- =========================================================================
             PROCESSING LOOP INTERFACE STATE
             ========================================================================= -->
        <?php if ($status !== 'completed' && $status !== 'failed'): ?>
            <div class="p-16 border border-dashed border-slate-200 rounded-2xl text-center space-y-5 pulse-glow" id="asyncProcessingCard">
                <i class="fa-solid fa-circle-notch animate-spin text-slate-900 text-3xl"></i>
                <div class="space-y-2 max-w-md mx-auto">
                    <h2 class="text-xl font-extrabold text-black tracking-tight">Processing Your Report</h2>
                    <p class="text-sm text-slate-800 leading-relaxed font-normal">We are processing your report. No need to wait here. We will send you email when report is ready</p>
                </div>
            </div>
            <script>
                document.addEventListener("DOMContentLoaded", () => {
                    const vid = "<?= urlencode($vid); ?>";
                    const statusCheckInterval = setInterval(async () => {
                        try {
                            const res = await fetch(`report_status.php?id=${vid}`);
                            const data = await res.json();
                            if (data.success && (data.status.toLowerCase() === 'completed' || data.status.toLowerCase() === 'failed')) {
                                clearInterval(statusCheckInterval);
                                window.location.reload();
                            }
                        } catch (e) { console.error(e); }
                    }, 2500);
                });
            </script>
        <?php elseif ($status === 'failed'): ?>
            <div class="p-12 border border-slate-200 rounded-2xl text-center space-y-5 max-w-2xl mx-auto bg-slate-50/50">
                <i class="fa-solid fa-triangle-exclamation text-rose-600 text-3xl"></i>
                <div class="space-y-3">
                    <h2 class="text-xl font-extrabold text-black tracking-tight">Report Generation Failed</h2>
                    <p class="text-sm text-slate-800 leading-relaxed font-normal text-left sm:text-center">We are sorry to inform you that our deep cognitive trace analysis core has failed to processing the requested targets. Cause may include insufficient data source, server error, ai response error. Try some time later with more social media data source.</p>
                </div>
            </div>
        <?php else: ?>
            
            <!-- =========================================================================
                 INCLUSION GATEWAY: ROUTE DATA PARSING OUT TO SUBMODULE
                 ========================================================================= -->
            <?php 
                if (file_exists('report_aianalysis.php')) {
                    include 'report_aianalysis.php';
                } else {
                    echo "<div class='p-4 bg-rose-50 text-rose-700 text-xs rounded-xl font-mono'>Error: Required submodule file 'report_aianalysis.php' missing.</div>";
                }
            ?>

        <?php endif; ?>

    </main>

    <?php if (file_exists('index_footer.php')) { include 'index_footer.php'; } ?>
</body>
</html>
